//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string carne { get; set; }
        public bool sexo { get; set; }
        public System.DateTime fechaNac { get; set; }
        public string email { get; set; }
        public string id { get; set; }
        public string apellidos { get; set; }
    }
}
